### ISSUE TITLE
Cache the position property

### ISSUE THREAD

**Issue by acrisci** [acrisci/playerctl#102]
When position is gotten, right now we do a dbus call to get the current position from the player.

Instead, calculate the current position based on previous status changes and clock monotonic time.

Maybe at some point in the future consider rate changes too.

This *might* improve position calculation with spotify a bit (it's totally broken now) although we still don't get a "seeked" event so it will still be wrong.

Add a `playerctl_player_get_position()` function to get the old behavior of hitting the dbus interface since I'm not confident we can rely on players to give the correct events to make this work correctly all the time.

In fact I'm not totally confident this will work at all, but it will be interesting to try. The interface specification seems to hint that we can do it.

**Comment by acrisci** [comment]
The algorithm goes like this:

Keep cached-position and cached-position-monotonic.

When play transitions to "playing", update cached-position-monotonic.

When we get the "seeked" signal, update cached-position and cached-position-monotonic.

When getting the position property,

  If paused then return cached-position

  If stopped return 0

  if playing return elapsed time of cached-position-monotonic and monotonic time plus cached-position

**Comment by triallax** [comment]
Is there a way to disable this caching? It doesn't take into account the playback speed, and (with mpv at least) while a video is still loading from the network, it starts incrementing the position even though nothing started playing yet.
