### ISSUE TITLE
Seek does not work properly

### ISSUE THREAD

**Issue by LinArcX** [acrisci/playerctl#110]
Hi. i want to seek current playing music. so i used this command:
playerctl position 5+
but it go back to position 5. how to properly seek the position?

**Comment by acrisci** [comment]
What does `playerctl --version` say?

**Comment by LinArcX** [comment]
v0.6.1

**Comment by acrisci** [comment]
That version does have the feature, but you should update to v2.0.1.

I can't reproduce this with vlc. What player are you using?

**Comment by LinArcX** [comment]
Yes. sure. i use cantata player.

**Comment by acrisci** [comment]
https://github.com/CDrummond/cantata/issues/1417

**Comment by LinArcX** [comment]
Thank you for bug report. i test it with v2.0.1. but nothing changed. wait for upstream fix.
