### ISSUE TITLE
Order of players for commands to act on is wrong

### ISSUE THREAD

**Issue by acrisci** [acrisci/playerctl#112]
```
playerctl --player=vlc,spotify play-pause
```

Acts on spotify first, but should act on vlc first.

**Comment by amithm7** [comment]
Can you make a release? Was waiting for this to be fixed!

**Comment by acrisci** [comment]
I'll start preparing a release. Can you test to make sure everything you use still works?

**Comment by amithm7** [comment]
Thank You. Yes, `playerctl --player=vlc,spotify play-pause` and `playerctl --player=spotify,vlc play-pause`, both  are working for me with 77b3175
