### ISSUE TITLE
Cannot control cmus.

### ISSUE THREAD

**Issue by LinArcX** [acrisci/playerctl#114]
Hi. i already install cmus instead of cantata. i want to control it with playerctl. but its not working.
Steps to reproduce:
1. Open cmus in a terminal emulator(Konsole)
2. Open a new terminal and run this command:
```
\> playerctl play
Connection to player failed: No players found
```
Hint: Music is playing, but seems playerctl cannot know about its existence!
Os: arch linux
playerctl: v0.6.1
cmus:  v2.7.1
wm: i3wm

**Comment by acrisci** [comment]
MPRIS support is new in cmus v.2.8.0.

https://github.com/cmus/cmus/releases/tag/v2.8.0-rc0

**Comment by annata83** [comment]
I like to report that running 2.8 and playerctld daemon does not read cmus at all on my Arch.
