### ISSUE TITLE
Suddenly stopped finding players

### ISSUE THREAD

**Issue by p4block** [acrisci/playerctl#116]
After an update to Arch's [testing] repos, [mainly containing systemd 240](https://www.archlinux.org/packages/?sort=&arch=x86_64&repo=Testing&q=&maintainer=&flagged=), playerctl cannot find any players at all. 

Can reproduce the issue in 3 different machines running similar minimal wm sessions (could be a session issue) but it worked just before the update.

**Comment by acrisci** [comment]
Playerctl did just get a major version bump, but it sounds more likely that the systemd upgrade did this.

List controllable players independent of playerctl like this:

```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep mpris
```

I bet you get no players.

Try adding this to your `.xinitrc` to launch your wm with some dbus variables some apps expect to get on the right bus:

```
exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) i3
```

Let me know how that goes.

**Comment by p4block** [comment]
Thanks for the quick response

As you guessed, that doesn't list any players.

Wrapping the bspwm binary with your command gets back an interesting result. 

```
Autolaunch requested, but X11 support not compiled in.
Cannot continue
```

This looks to me like it could be a packaging issue or bug upstream

**Comment by acrisci** [comment]
Yeah, we'll need to figure out some way for all the apps to know the location of the bus and document it. I wonder why they removed that X11 compile option.

One candidate might be to use `dbus-run-session` in place of `dbus-launch.

To see if any of this will really work, try setting the environment variables manually in xinitrc.

```
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${UID}/bus
```

**Comment by p4block** [comment]
Hello

I managed to get playerctl to work by wrapping `bspwm` with `dbus-run-session bspwm` and calling that from the xsession file. (I don't use xinitrc but it worked with that too)

It's definitely related to the dbus socket placement, its location on a fresh login was:

```
echo $DBUS_SESSION_BUS_ADDRESS 
unix:abstract=/tmp/dbus-YrjgcfdkrK,guid=b4f2bed01d0cbd15519bccf05c2f8668
```

Setting the address to `unix:path=/run/user/${UID}/bus` made it not work again.

Now, it's not completely fixed because my polybar running as systemd user service still cannot find players. The service probably has another location for it, or it is empty.

**Comment by p4block** [comment]
I can (still) run all my X11 apps from within user services, and they are mostly tied to session (I've definitely seen other behavior though).ones such as redshift which iirc uses dbus to get the location from geoclue, so far it's just playerctl the one having issues.

I will investigate the X11 support thing though and/or hardocing the environment variables into playerctl's service

**Comment by p4block** [comment]
Issue is resolved as of latest Arch's systemd revision. Issue can be closed :)
