### ISSUE TITLE
Throw an exit code when no players are running

### ISSUE THREAD

**Issue by UtkarshVerma** [acrisci/playerctl#119]
I was currently writing a script for displaying `playerctl` details in i3bar and wanted to develop a case where the script shouldn't execute, that is when no players are active. My first thought was to use the `playerctl status` command and match it with `"No players found"` and it worked, but I wasn't able to suppress the excess output associated with it, that is `"No players found"`. I also checked if playerctl throws an exit code when executing `playerctl status` in absence of any music players, and it doesn't. It always exits with zero exit code.  
Therefore it would be great if the functionality of returning an error code other than `0` were implemented since that would enable me to use the following:
```bash
#Exit script if no players running
playerctl status 2>/dev/null || exit 3;
```

**Comment by acrisci** [comment]
Yeah seems reasonable.

In the meantime:

```
if [[ $(playerctl status 2>&1) = "No players found" ]]; then
    exit 3
fi
```

**Comment by UtkarshVerma** [comment]
@acrisci That's exactly what I'm using as a  workaround currently.
