### ISSUE TITLE
Reopen #79, option to open from URI doesn't work with Spotify. 

### ISSUE THREAD

**Issue by maikeldotuk** [acrisci/playerctl#122]
issue #79 talks about a new feature to open from a local file or an URI. Yet it doesn't work with Spotify, which is probably one of the most important reasons to use it. Could you guys please add this functionality.

**Comment by acrisci** [comment]
Spotify is getting the command and ignoring it. Since it's not open source, I can't investigate further.

Please contact spotify customer support.

**Comment by maikeldotuk** [comment]
I see thanks anyway. Could I ask you an alternative? On 24 Feb 2019 14:31, Tony Crisci <notifications@github.com> wrote:Spotify is getting the command and ignoring it. Since it's not open source, I can't investigate further.
Please contact spotify customer support.

**Comment by acrisci** [comment]
If you use an open source client, I can go and fix the mpris implementation in the client when there is a problem. I've done that to a few players.

I haven't actually used any of these, but these are two examples that say they work with spotify and should work with playerctl.

https://github.com/mopidy/mopidy

https://www.clementine-player.org/

**Comment by maikeldotuk** [comment]
Perfect thank you, will try later today and dn let you knowbOn 24 Feb 2019 15:28, Tony Crisci <notifications@github.com> wrote:If you use an open source client, I can go and fix the mpris implementation in the client when there is a problem. I've done that to a few players.
I haven't actually used any of these, but these are two examples that say they work with spotify and should work with playerctl.
https://github.com/mopidy/mopidy
https://www.clementine-player.org/

**Comment by maikeldotuk** [comment]
I've tried Mopidy. I can play music through the Mopify interface but not with playerctl. 

Everytime I try, for example: 

`
playerctl open spotify:track:3iNizDntew1elWNnMqaAAw 
`

This is what I get:

`
Failed to lookup "spotify:///track:3iNizDntew1elWNnMqaAAw": Failed to get link from Spotify URI: dbus.String(u'spotify:///track:3iNizDntew1elWNnMqaAAw')
`

**Comment by maikeldotuk** [comment]
Update, tried clementine. It says GStreamer is missing a plugin???

**Comment by maikeldotuk** [comment]
This is the weirdest error ever. In clementine I can write the exact same thing on the menu "playlist" then "add stream" and it works but with playerctl it doesn't. 

Check screenshot 

![2019-02-24-233622_1024x768_scrot](https://user-images.githubusercontent.com/29461493/53307146-576fce00-388d-11e9-800f-73b92a78bc37.png)

**Comment by maikeldotuk** [comment]
Right, I've found a workaround but this one implies doing it out of playerctl entirely. 
With clementine it works out of the box with

`clementine -l spotify:track:3iNizDntew1elWNnMqaAAw`

I don't know why playerctl changes it to spotify:///track:3iNizDntew1elWNnMqaAAw but that seems to be the problem.

**Comment by maikeldotuk** [comment]
In case of any interest on what Ineed this for, see below:

[The Code](https://gist.github.com/maikeldotuk/6ce2fd3aa6a41e9060274894aa102170)

**Comment by acrisci** [comment]
Yeah this definitely could be a bug in playerctl. I'll look into it.

**Comment by maikeldotuk** [comment]
Sounds great. Thank youOn 25 Feb 2019 02:09, Tony Crisci <notifications@github.com> wrote:Yeah this definitely could be a bug in playerctl. I'll look into it.

**Comment by acrisci** [comment]
I pushed a change that makes `playerctl open spotify:track:3iNizDntew1elWNnMqaAAw` work with the actual spotify client and I believe it will fix the issues with the other players.

Testing clementines dbus implementation now, since I saw other errors in your report as well.

**Comment by maikeldotuk** [comment]
Right, I'm going to try from my side and report back. Give me a couple of minutes.

**Comment by maikeldotuk** [comment]
# Yay!!! It works, partyyyyy :D 

Confirmed with:
* Mopidy (spotify)
* Clementine (spotify)
* Spotify Desktop latest dev build

Basically you've fixed it and it now works with everything. You're amazing @acrisci . Back to one command to rule them all, thank you very much.

**Comment by acrisci** [comment]
:sunglasses:
