### ISSUE TITLE
"No players found" not returned as string in status

### ISSUE THREAD

**Issue by kaustubhhiware** [acrisci/playerctl#125]
When some media is playing, `playerctl status` returns appropriate string which can be logged, but not when nothing is playing. Basically,

```
$ x=$(playerctl status) # When vlc is playing
$ echo $x
Playing
$ x=$(playerctl status) # When vlc is paused
$ echo $x
Paused
$ x=$(playerctl status) # No media
No players found
$ echo $x

$
```

This was working fine till the most recent update, version **v2.0.1** breaks this.

OS: Arch Linux, kernel `x86_64 Linux 5.0.0-arch1-1-ARCH`
The fixes mentioned in #119 and elsewhere do not work. I'm using this to dictate buttons in polybar.

**Comment by Baviste** [comment]
This is because the status is sent in stderr in that case.
You can redirect stderr to stdout to solve your problem:

    $ x=$(playerctl status 2>&1)
    $ echo $x
    No players found

**Comment by kaustubhhiware** [comment]
Thanks for the fix, it works well !
Closing the issue now.

**Comment by kaustubhhiware** [comment]
What finally worked for me was the following:

```
player_status=$(playerctl status 2>&1)

if [ "$player_status" == "No players found" ] ; then
	echo "Off"
else
      echo "On"
fi
```
