### ISSUE TITLE
Add template helper function for pango markup escaping

### ISSUE THREAD

**Issue by un-def** [acrisci/playerctl#133]
I use `playerctl metadata` with i3bar and forced to use `none` markup mode because any special char (`<`, `>`, `&`, etc.) in metadata field breaks `pango` markup.

It would be convenient to have some helper function to encode special chars to corresponding entities (e.g., `<` → `&lt;`). This would allow to use pango markup safely, for example:

```
playerctl --follow metadata --format '<b>pango_escape({{artist}})</b> — pango_escape({{title}})'
```

I guess this can be done quite easily with `g_markup_escape_text()`.

**Comment by acrisci** [comment]
Yeah seems like a good feature. I also use [playerctl with i3bar](https://github.com/acrisci/i3-dstatus/blob/master/i3dstatus/generators/playerctl) so I would use this.

Instead of `pango_escape`, I would call it `markup_escape` or maybe `xml_escape` and the format string would look like this:

```
'<b>{{markup_escape(artist)}}</b> — {{markup_escape(title)}}'
```

**Comment by acrisci** [comment]
It's in latest and has tests but needs documentation.

**Comment by un-def** [comment]
It's great! I just did a quick check, the new helper works well.
