### ISSUE TITLE
Any chance of an Ubuntu x86_64 package please?

### ISSUE THREAD

**Issue by feoh** [acrisci/playerctl#14]
I tried building from source, which worked, but as you mentioned somewhere getting it rigged into your distro can be a challenge, so the media keys didn't work.

Any chance of an Ubuntu x86_64 package please? :) I also would be delighted to Flattr or gittip you for this work :)

**Comment by acrisci** [comment]
I just added a debian package to the [releases](https://github.com/acrisci/playerctl/releases) page.

The latest debian package is [here](https://github.com/acrisci/playerctl/releases/download/v0.4.2/playerctl-0.4.2_amd64.deb).

Let me know if that works.
