### ISSUE TITLE
No metadata on Spotify

### ISSUE THREAD

**Issue by fran-penedo** [acrisci/playerctl#15]
On playerctl version 0.4.2-1, spotify version 0.9.17.1-1, running playerctl metadata outputs no metadata. Other commands (play, pause) work with spotify, and metadata works with other players (tested it with vlc).

**Comment by fran-penedo** [comment]
Correction: playerctl volume doesn't work either. I can set the volume and it will output the last one I set, but no change is made to spotify's volume. Not sure if this is related to the metadata problem though.

**Comment by fran-penedo** [comment]
Nevermind, apparently it won't work when notifications are disabled for spotify (unrelated to playerctl). Volume still doesn't work, although now that I took a look at the source code it seems like it has more to do with spotify and dbus. Feel free to close this.

**Comment by acrisci** [comment]
Spotify's dbus support is not great right now which is unfortunate. I would suggest emailing support and asking for them to improve it.

**Comment by p3lim** [comment]
[This person](https://bbs.archlinux.org/viewtopic.php?id=134635) seemed to get it just fine with the following:
`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`

**Comment by p3lim** [comment]
[This person](https://bbs.archlinux.org/viewtopic.php?id=134635) seemed to get it just fine with the following:
`dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`
