### ISSUE TITLE
Volume deltas (+/- by a certain amount)

### ISSUE THREAD

**Issue by acrisci** [acrisci/playerctl#16]
Change volume by a certain amount with volume +/-.

This can be used in volume up and volume down key bindings.

Example:

    playerctl volume +0.1 # increase volume by 10%
    playerctl volume -0.2 # decrease volume by 20%

**Comment by beanaroo** [comment]
I gave this a try today. Unfortunately:
`playerctl volume 0.1+` has no effect with no output.
`playerctl volume 0.1-` warns: 
```(playerctl:15086): GLib-GObject-WARNING **: value "-0.100000" of type 'gdouble' is invalid or out of range for property 'volume' of type 'gdouble'```

**Comment by acrisci** [comment]
Hey @beanaroo would you make a dedicated issue for this and we'll talk about it there.
