### ISSUE TITLE
Doesn't work with Banshee

### ISSUE THREAD

**Issue by MightyPork** [acrisci/playerctl#17]
Maybe I'm doing something wrong, but I can't control Banshee with playerctl. It does not see the player, the list option shows "no players".

It works fine for Clementine, Spotify and Amarok.

Is there anything I can try to get it working - or help you add the support?

---
version 0.4.2, built from AUR
Arch 64bit, Xfce4

**Comment by acrisci** [comment]
Here is how to enable it.

Edit > Preferences > Extensions > Utilities > MPRIS D-Bus interface

Make sure that checkbox is checked.

Why is it not enabled by default? I don't know. Maybe you can take that issue up with them.

Maybe we should add some documentation on how to enable support for certain media players.

**Comment by MightyPork** [comment]
Thanks, that worked perfectly. Kinda silly that it's even toggleable…

Yeah perhaps a little note in the README.md would be really useful.

Thanks a lot!
