### ISSUE TITLE
on_metadata dont work with spotify testing

### ISSUE THREAD

**Issue by BluscreamFanBoy** [acrisci/playerctl#18]
I install everything that I need on debian jessie with the repository:
deb http://repository.spotify.com testing non-free
But the function is not on_metadata is not working. Even the event doesn't work.

**Comment by acrisci** [comment]
Hey, sorry for the late reply on this.

What version of spotify are you using?

**Comment by Dinoshauer** [comment]
Hey, I'm guessing this is the same problem as it's the beta version that's being used :)

Here's my info (hope it helps):

    $ playerctl --version
    v0.4.2
    $ playerctl status
    Not available

`aur/spotify-beta 1.0.14.124-2 (36, 10.69)`

**Comment by acrisci** [comment]
Closing in favor of #20.
