### ISSUE TITLE
mpv Support?

### ISSUE THREAD

**Issue by LNJplus** [acrisci/playerctl#25]
I'm very often using mpv as player for videos. I noticed that playerctl don't supports it.
Would be very nice if you could add it (if possible)! :smiley:

**Comment by vivien** [comment]
Does MPV support MPRIS?

**Comment by LNJplus** [comment]
I just know that it is based on mplayer.

**Comment by ids1024** [comment]
mpv-player/mpv#661

Mpv does not support mpris, but there is a lua script for it that adds mpris2.

**Comment by LNJplus** [comment]
Ahhh okay what does this mean for me?
But thanks for your "recherches".

**Comment by ids1024** [comment]
The script is mentioned in the discussion of that issue.
https://github.com/dodo/lua-mpris#mpv
Set That up, and mpv should work with playerctl.

**Comment by LNJplus** [comment]
Ok thanks! Should I close this issue?

**Comment by ids1024** [comment]
Yes, probably.

**Comment by yobert** [comment]
In case anyone else stumbles on this later: Easier than the lua setup is to use this new plugin for mpv somebody wrote: https://github.com/hoyon/mpv-mpris
