### ISSUE TITLE
Tomahawk player not detected as valid player

### ISSUE THREAD

**Issue by craftyguy** [acrisci/playerctl#31]
[Tomahawk](https://github.com/tomahawk-player/tomahawk) is not detected and not controled by playerctl, even though it supports mpris.

**Comment by acrisci** [comment]
works for me

**Comment by craftyguy** [comment]
Was there a recent commit to fix this? I didn't see anything obvious in the commit log... I'm using v0.5.0.

**Comment by acrisci** [comment]
I'm using tomahawk 0.8.4 built from AUR. No recent change to playerctl would fix this.

**Comment by craftyguy** [comment]
I'm using tomahawk-qt5 from air, and playerctl says there are no valid players found.

**Comment by craftyguy** [comment]
I'm using tomahawk-qt5 from aur, and playerctl says there are no valid players found.

**Comment by acrisci** [comment]
Try this

```
dbus-send --session           \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply               \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames
```

You should see `string "org.mpris.MediaPlayer2.tomahawk"` in the list. I do.

**Comment by craftyguy** [comment]
Yea I see tomahawk, and furthermore it appears to be working. I think the actual issue is that tomahawk goes AWOL when my system resumes from suspend.. causing playerctl and even attempts to control it directly to fail. Sorry for the false alarm!
