### ISSUE TITLE
Errors with gpmdp ( google-play-music-desktop-player )

### ISSUE THREAD

**Issue by kingy9000** [acrisci/playerctl#35]
Playerctl always outputs the following when I control [google-play-music-desktop-player](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-), as identified by `playerctl -l`. I'll refer to it as gpmdp from now.

```
(playerctl:13598): GLib-GIO-WARNING **: Received property Rate with type y does not match expected type d in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property Volume with type y does not match expected type d in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property Position with type u does not match expected type x in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property MinimumRate with type y does not match expected type d in the expected interface

(playerctl:13598): GLib-GIO-WARNING **: Received property MaximumRate with type y does not match expected type d in the expected interface
```

Playerctl is able to control gpmdp successfully but will cause the shell to get stuck after doing so and prevent a program that's supposed to run afterwards from running.

For example, I run a command to update my status bar with the current playing song.

Thanks for reading and let me know if any extra info is needed.

EDIT: I am running playerctl v0.5.0 and gpdmp v3.6.0. There are no new commits to the repo since v0.5.0 came out so I assume there are no differences between the release and the git version.

**Comment by ChrisB9** [comment]
I am getting the same warning, though it only stucks by the commands pause, play-pause and stop
but its printing this by each mpris-command

`(playerctl:10910): GLib-GIO-WARNING **: Received property Rate with type y does not match expected type d in the expected interface

(playerctl:10910): GLib-GIO-WARNING **: Received property Volume with type y does not match expected type d in the expected interface

(playerctl:10910): GLib-GIO-WARNING **: Received property Position with type u does not match expected type x in the expected interface

(playerctl:10910): GLib-GIO-WARNING **: Received property MinimumRate with type y does not match expected type d in the expected interface

(playerctl:10910): GLib-GIO-WARNING **: Received property MaximumRate with type y does not match expected type d in the expected interface
`

**Comment by hatzel** [comment]
Any news on this? I would be willing to devote some time to figuring this out and fixing it.

**Comment by acrisci** [comment]
@hatzel go ahead. If you have questions, please don't hesitate to ask.

**Comment by hatzel** [comment]
Okay, sorry for taking so long. It appears that this is not strictly speeking a bug in playerctl. Instead it seems that gpmdp is sending data not conforming to the org.mpris.MediaPlayer2 protocol.

I used the tool dbus-mointor to get inspect some of the communication.
See this extract of a relevant section:

```
      dict entry(
         string "MinimumRate"
         variant             byte 1
      )
      dict entry(
         string "MaximumRate"
         variant             byte 1
      )
```

As you can see these datatypes are bytes (which are called type y in GLib) while the [documentation](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html) specifies that the value should be a double.

Just to verify this I looked at an app that worked with playerctl (spotify) and it actually sends the specified datatypes:

```
      dict entry(
         string "Rate"
         variant             double 1
      )
      dict entry(
         string "MinimumRate"
         variant             double 1
      )
```
As a course of action I would recommend fixing this in gpmdp (I will actually do this).
But I also think that playerctl should handle incorrect data better, I will look into writing up a pull request for this.

**Comment by WolfangAukang** [comment]
Hello, any update on this issue? I have seen [GPMDP uses their fork of mpris-service](https://github.com/GPMDP/mpris-service/blob/master/index.js), so maybe this can be helpful

**Comment by hatzel** [comment]
I took a deep dive into this issue but I didn't really get anywhere.[ This issue explains the underlying problem in node dbus](https://github.com/Shouqun/node-dbus/issues/143), but nobody there is answering and it is not an easy fix.

**Comment by fcastilloec** [comment]
As a workaround, at least only for `Rate`, `MinimumRate` and `MaximumRate`. I'm passing the value `1+1e-15`. This prevent `dbus` from thinking it's a `byte` or even an `int`, and mpris sees the value as a 1 anyway.
For the position, that has no fixing on this side, only on the `dbus` module itself, or `mpris` module switching to a different `dbus` module that implements int64

**Comment by SicariusNoctis** [comment]
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/2741

**Comment by acrisci** [comment]
I fixed it!

https://dubstepdish.com/index.php/2019/03/17/the-great-node-mpris-project/
