### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by bnt0** [acrisci/playerctl#39]
The library documentation seems to be unavailable: http://www.isitdownrightnow.com/dubstepdish.com.html

Is there an alternative place to get it?

**Comment by acrisci** [comment]
My server crashed during a system update yesterday and I need to fix it. I will try to fix it this weekend.

In the mean time, you can build the documentation with

```
./autogen.sh
./configure --enable-gtk-doc
make
```

Then

```
cd doc/reference/html
python3 -m http.server
```

And go to the site.

**Comment by acrisci** [comment]
It's back up now.
