### ISSUE TITLE
GLib-GIO-WARNING **: Received property Rate with type y does not match expected type d in the expected interface

### ISSUE THREAD

**Issue by orschiro** [acrisci/playerctl#40]
Dear @acrisci,

Thank you for your work!

I just installed the latest deb package on Ubuntu 16.10 to test it.

Can you help me with the following error?

Yours,

Robert

```
orschiro@x230:~$ playerctl play-pause

(playerctl:15525): GLib-GIO-WARNING **: Received property Rate with type y does not match expected type d in the expected interface

(playerctl:15525): GLib-GIO-WARNING **: Received property Volume with type y does not match expected type d in the expected interface

(playerctl:15525): GLib-GIO-WARNING **: Received property Position with type u does not match expected type x in the expected interface

(playerctl:15525): GLib-GIO-WARNING **: Received property MinimumRate with type y does not match expected type d in the expected interface

(playerctl:15525): GLib-GIO-WARNING **: Received property MaximumRate with type y does not match expected type d in the expected interface
```

**Comment by acrisci** [comment]
Hi,

This probably means your player is not imlementing the dbus interface in the way that is expected.

What player are you using?

**Comment by orschiro** [comment]
Dear @acrisci,

I experienced this with https://github.com/Quacky2200/Spotify-Web-Player-for-Linux

**Comment by fa7ad** [comment]
Any update on this issue? I'm facing the same problem with mopidy

**Comment by fa7ad** [comment]
@acrisci One of my scripts broke because of this. I ended up redirecting the stderr to /dev/null as a workaround

**Comment by acrisci** [comment]
Why are you listening to stderr? It's only supposed to be for diagnostic messages like that.

**Comment by fa7ad** [comment]
@acrisci I wasn't specifically filtering out which output stream to capture. just capturing the output altogether and then running other stuff based on that.

**Comment by fa7ad** [comment]
@acrisci I'd love to help with the JS bug, where should I be looking? I wanna have a crack at it while you're busy :smile:

**Comment by acrisci** [comment]
https://github.com/emersion/mpris-service/issues/1

**Comment by acrisci** [comment]
https://github.com/Quacky2200/Spotify-Web-Player-for-Linux/issues/90
