### ISSUE TITLE
Support for Totem Video Player?

### ISSUE THREAD

**Issue by orschiro** [acrisci/playerctl#41]
Dear @acrisci,

I am wondering whether Totem Video Player is supported?

Yours,

Robert

![image](https://cloud.githubusercontent.com/assets/170947/24096583/866a62f4-0d62-11e7-8799-8d287c1b3ac9.png)
_Playerctl saying no supported players found despite Totem playing an mp3 file._

**Comment by acrisci** [comment]
I think there is a plugin for Totem that you need to activate in order to get it to work. Search for "totem mpris plugin".

**Comment by orschiro** [comment]
Thank you very much. :-)

![image](https://cloud.githubusercontent.com/assets/170947/24114878/f5a399f8-0da1-11e7-8ff3-7b7fcda5750b.png)
