### ISSUE TITLE
signed releases

### ISSUE THREAD

**Issue by shibumi** [acrisci/playerctl#42]
Hello,
I am the maintainer of your software in Arch Linux. I would like to suggest to sign the releases. You can find a tutorial for it here: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thanks

**Comment by acrisci** [comment]
Thanks, I'll look into that for the next release.

**Comment by acrisci** [comment]
2.0.2 has a signed release with the public key I have attached to my github account. I'll do this from now on.
