### ISSUE TITLE
Timeout was reached

### ISSUE THREAD

**Issue by jampow** [acrisci/playerctl#43]
Hi,

My `playerctl play-pause` is returning the message `An error ocurred: Timeout was reached`. My spotify version is 1.0.52.717.g2f08534a.

What could I do to fix this? Is someone getting the same error?

Tks

**Comment by acrisci** [comment]
Hi,

Use `d-feet` to test spotify's dbus interface directly. If you still get the same error then it's their issue. If you don't, I will help you debug the issue.

**Comment by jampow** [comment]
TKS for the help @acrisci , I rebooted and the playerctl back to work. Probably some dbus problem.
