### ISSUE TITLE
Error with unknown variable -e

### ISSUE THREAD

**Issue by MartorSkull** [acrisci/playerctl#50]
When trying to execute the `playerctl stop` command from a service, so the music pauses when my compuer goes into suspended mode, the `journalctl` command shows this error:
```
 playerctl[27568]: Option parsing failed: Unknown option -e
```
and none of the other commands run. The service file is:
```
[Unit]
Description=User suspend actions
Before=sleep.target

[Service]
User=%I
Type=forking

Environment=DISPLAY=:0
ExecStart=/usr/bin/playerctl stop
ExecStart=/usr/bin/locker
ExecStartPos=/usr/bin/sleep

[Install]
WantedBy=sleep.target
```
I think the command should take the varable but not do anything with it. Just to make it usable in the Service files.

**Comment by acrisci** [comment]
I don't understand where the `-e` is coming from in your unit file. Are you sure this isn't a systemd bug?

**Comment by MartorSkull** [comment]
To pass the -e flag is a normal behavior of the systemd for what I've read. So i thought to come and ask here.

**Comment by MartorSkull** [comment]
I'm so sorry. i misplaced a file in the /usr/bin and overwrite the playerctl file. I'll close this issue. Thanks for your time.
