### ISSUE TITLE
playerctl status with Spotify

### ISSUE THREAD

**Issue by Drakota** [acrisci/playerctl#51]
Hi, I'm using i3wm and wanted to display a notification when I play/pause my player. I've made a little script to achieve this with `dunstify` that looks like this : 
```
#!/bin/bash
PLAYERSTATUS=$(playerctl status)
if [[ "$PLAYERSTATUS" == "Playing" ]]
then
	dunstify -p -r 3 -u low -i /usr/share/icons/Notifications/pause.png  "Player" "Paused";
elif [[ "$PLAYERSTATUS" == "Paused" ]]
then
	dunstify -p -r 3 -u low -i /usr/share/icons/Notifications/play.png "Player" "Playing";
else
	dunstify -p -r 3 -u low "Player" "$PLAYERSTATUS";
fi
```
For some reason, in Spotify, when it's the active player, I had to switch the status and display the notification with the reverse status, because there seems to be a delay between the display of the notification and the change of status making the notification display the reversed status. Now, when I tried with another player like MPV, I get Paused when Playing and Playing when Paused, so MPV is working as intended, why not Spotify?

**Comment by acrisci** [comment]
The latest version of spotify doesn't even give me a dbus interface right now.

**Comment by k1-hedayati** [comment]
That's sad, I've this issue too

**Comment by ofesseler** [comment]
On the latest Arch Linux system with installed spotify 1.0.80.480-1 and playerctl 0.6.0-1 it works as expected. 
Is this issue fixed?

**Comment by nightbluepn** [comment]
I am running arch with playerctl 0.6.0-1 and spotify 1.0.80.480-1, playerctl -l gives nothing (works with vlc)

**Comment by gkroon** [comment]
Same issue on Gentoo with media-sound/playerctl 0.5.0 and media-sound/spotify 1.0.80.

**Comment by ranisalt** [comment]
Same issue as above with playerctl 0.6.1 and Spotify 1.0.80 on Arch Linux

**Comment by acrisci** [comment]
I think I've figured this out.

If you don't use a session manager, try adding `dbus-launch --exit-with-session` before starting your wm.

For instance, in your `/.xinitrc` file, end the file with `exec dbus-launch --exit-with-session i3`.

**Comment by orestisf1993** [comment]
We've had multiple bug reports caused by `--exit-with-session`: https://github.com/i3/i3/issues/2979, https://github.com/awesomeWM/awesome/issues/1064, https://github.com/ch11ng/exwm/issues/210

**Comment by acrisci** [comment]
Ah ok.

I can actually get it to reuse the one that systemd uses like this:

```
exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) i3
```

So no need to exit because the session doesn't own it.

**Comment by ZargEzey** [comment]
> Ah ok.
> 
> I can actually get it to reuse the one that systemd uses like this:
> 
> ```
> exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) i3
> ```
> So no need to exit because the session doesn't own it.

Hello, I just comment to say thank you @acrisci for your comment here.

I have problem that bug me for a couple of days with Spotify notifications, using latest client on KDE Plasma 5. Suddenly notification they stop to work, I could not seem to figure out why. I try so much things without success. Finally I try out playerctl (which i see now is a nice tool). I see that Spotify was getting no dbus interface as you said, meaning no players were being found, vlc and others worked fine however. This lead me finally to this thread and your comment.

When I use exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) spotify all notifications work again, and of course playerctl can now see spotify player. No idea what cause notifications to stop work but thank you very much!

**Comment by nightbluepn** [comment]
turns out i was an idiot and forgot i use spotify with firejail.
Apparently they started blocking dbus after an update, 
https://github.com/netblue30/firejail/issues/2098
was the fix for me, now playerctl -l shows spotify again.

**Comment by ranisalt** [comment]
@nightbluepn you can run firejail with `--ignore=nodbus` to avoid that issue while keeping safe.
