### ISSUE TITLE
What is the default player? Or, --first-player-of=A,B,C

### ISSUE THREAD

**Issue by SimonSapin** [acrisci/playerctl#54]
In the README:

>  If no player is specified, it will use the first player it can find.

How is it determined which one is first? Is it possible to have some influence over that?

Alternatively, what do you think of adding a command-line parameter that specifies multiple player name, and the command would be sent to the first of these that can be found? (That way the list specifies a priority order.)

If this sounds good, could you point me to appropriate parts of the code where I could start making a patch for it?

(My use case is that I keep Rhythmbox open semi-permanently in the background for music and pause it when I want to listen to something else. That something else might be another player supported by playerctl. If so, I’d like commands to go to that player until it is closed.)

**Comment by acrisci** [comment]
I think it will go in reverse alphabetical order of the dbus name.

We have `--all-players` now which will command all the players. and I think you can pass `,` between player names to command multiple players at the same time.

But these will send the command to all the players, not the first one it can find. Is that good enough for your use case?

**Comment by SimonSapin** [comment]
Sending the same command to all/multiple players would work for the "pause" command, but not for "play" (resume from pause). I want to send it to only one player. Ideally, the one would be chosen based on a stack of which has been most recently playing. But I imagine that’s more tricky, I can settle for hard-coding a priority ordering.

**Comment by acrisci** [comment]
What would you propose as an interface for playerctl to do what you want?

**Comment by SimonSapin** [comment]
What do you think of `--first-player-of=smplayer,rhythmbox` on the command-line?

**Comment by FichteFoll** [comment]
I'm also interested in the stack of most recently playing players, but I believe that this isn't for the CLI to solve, so I'd need a daemon listening to events anyway. However, once I have that and store it in some file, I can easily pipe that into a call to playerctl with `--first-player` to resume the last playing player without also monitoring when they close/exit (not sure if that info is provided in the library as I couldn't find any docs on it). Would be nice if it also returned which player it selected in that case.

**Comment by acrisci** [comment]
@FichteFoll right now the "default" player is kind of arbitrary with no defined order. Using the last active player would be ideal if we could figure out a reliable and cross-platform way to do it. Maybe reading dbus logs? It might not be possible though.

You can make a daemon to do what you want with the playerctl library. See the readme for an example script.

I noticed my documentation was down. It is again hosted at https://dubstepdish.com/playerctl . You can see a complete list of signals you can subscribe to there and commands.

**Comment by acrisci** [comment]
I think I'm just going to make this the default behavior of the `--player` flag when multiple players are passed. Then you can select all the players in the list with `--all-players --player=player1,player2` which would be the current behavior. Then add an `--ignore-player` flag (#2) to ignore players. Then I think anything should be possible with the fewest possible flags.

**Comment by acrisci** [comment]
Vlc and Gwenview do the exact same thing with the instances so this might be some kind of standard. I think it makes sense to target an instance when no player exactly matches the name. In that case, look for `$name.instance$num`.

**Comment by FichteFoll** [comment]
It is: https://specifications.freedesktop.org/mpris-spec/2.2/index.html#Bus-Name-Policy

**Comment by acrisci** [comment]
Oh good that makes it really easy then.

**Comment by FichteFoll** [comment]
So, `mpv` is actually an interesting case because the script that implements mpris for it somehow keeps an mpv bus around even if the original instance was closed. Or so it seems, from opening and closing a couple with `watch playerctl -l` running. Unfortunately, the order of players found differs widely and certainly does not depend on the bus name, since sometimes instances were listed above and sometimes below the "original" `mpv`.

Not considering that, this change works exactly as expected. :+1:
