### ISSUE TITLE
Package for Fedora

### ISSUE THREAD

**Issue by barondem** [acrisci/playerctl#56]
Hi! Could you please package playerctl for Fedora in order for its users to take advantage of it without having to compile it? A COPR repository would be even bettter.
Thanks in advance!

PS: Another idea could be creating a flatpak for it.

**Comment by acrisci** [comment]
Yeah I agree we should do this. If you would like to be a package maintainer, I would appreciate the help.

**Comment by acrisci** [comment]
I put an rpm on in the releases.
