### ISSUE TITLE
Position not updates

### ISSUE THREAD

**Issue by kazemihabib** [acrisci/playerctl#58]
```
def showPosition():
  threading.Timer(1.0, printit).start()
  print(player.props.position)

showPosition()
```
Just shows the same position every 1 second
The only solution I found is recreate the player object every time.
```
def showPosition():
  threading.Timer(1.0, printit).start()
  player = Playerctl.Player(player_name='clementine')
  print(player.props.position)

showPosition()
```
Any other solution ?

**Comment by acrisci** [comment]
I've known about this issue for awhile. Not really sure how to fix it.

https://github.com/acrisci/playerctl/blob/8caf9a31f2420b73ff226d89a0ebdc7cb7f724da/playerctl/playerctl-player.c#L205-L213

**Comment by msudgh** [comment]
Is possible to have a property with the name `elapsed_time`?

**Comment by acrisci** [comment]
Eh, let's just not use the cache for getting that property.

https://github.com/acrisci/playerctl/blob/27bda74e689679c008bc410540610acb0bcdd047/playerctl/playerctl-player.c#L205-L240

**Comment by msudgh** [comment]
@acrisci I rebuild the playerctl and didn't work.

**Comment by acrisci** [comment]
Can you post your script and what player you are using so I can test it?

**Comment by msudgh** [comment]
I just test python binding and also cli interface return `0` value while Spotify is running and playing.

**Comment by acrisci** [comment]
Oh that's probably a spotify issue then. Try debugging it with d-feet or something, but there's probably nothing I can do because they don't take care of their mpris interface as well as they used to.

**Comment by msudgh** [comment]
Yep, it's about Spotify. I don't have enough vision about MPRIS API, Could provide a property to return the current elapsed time? I mean by this property, it will be possible to break having a dependency on the application for the current position of seek bar.

**Comment by acrisci** [comment]
I'm working on this now, but it's not ever going to work correctly. We don't get a "seeked" event, so the elapsed time will be wrong when you move the position in the track or start from a position that isn't the beginning.
