### ISSUE TITLE
Please consider adding a Changelog

### ISSUE THREAD

**Issue by knowledgejunkie** [acrisci/playerctl#60]
Currently key changes between versions is available on the Github releases page.

Adding a changelog file to the project would be very useful not only to end-users for quickly understanding changes between releases (e.g. when using tarballs), but also for Linux distribution packagers who can automatically include the changelog with packaged versions of the software.

**Comment by acrisci** [comment]
Yeah that makes sense. :+1:

**Comment by acrisci** [comment]
Changelog added.
