### ISSUE TITLE
Add option to output metadata as JSON 

### ISSUE THREAD

**Issue by b0o** [acrisci/playerctl#64]
I'm having a bit of a tough time parsing the metadata output. 

According to #22, it's formatted in "GVariant", which is rather obscure and lacks many utilities to assist with parsing it.

It seems a more standard format like JSON would make more sense. 

Adding a flag like `--output=FORMAT` where `FORMAT` is one of `json`, `gvariant`, etc. and keeping `gvariant` as the default would ensure this change wouldn't break any existing dependent code.

**Comment by acrisci** [comment]
Yeah, that is a bit awkward and you bring up some good points that the current output format is weird. But I think json is a bit overkill if you're just trying to print something like "artist -title" or something.

I've thought of a few ways to make this easier. Let me know if you like these ideas better than the json.

Idea 1: tsv output format

`$ playerctl metadata` gives tsv output which is human readable and fairly machine readable. It gets a little tricky with lists though.

```
xesam:title      Rise
xesam:artist    Katy Perry
xesam:album  Rise
...
```

Idea 2: format string

Playerctl metadata queries accept a format string like this:

```
$ playerctl metadata --format='%xesam:artist - %xesam:title'
```

This prints `Katy Perry - Rise`.

**Comment by b0o** [comment]
What about just modifying the `playerctl metadata [KEY]` command to accept multiple keys?

E.g.

```sh
$ playerctl metadata xesam:artist xesam:title mpris:length xesam:userRating
Bonobo
Outlier
475000000
1
```

**Comment by acrisci** [comment]
I think these are all good ideas :) let's break this up into separate issues and close this since we can do the same thing without a dependency. If you want to work on any of them feel free to pick it up.

**Comment by b0o** [comment]
Sounds good, made #68 and closing this.
