### ISSUE TITLE
`playerctl` unable to get `track id` from Audacious

### ISSUE THREAD

**Issue by UtkarshVerma** [acrisci/playerctl#65]
I was testing out seeking capabilities of `playerctl` with Audacious until the following happened:
```sh
$ playerctl position 10 +   
Could not execute command: Could not get track id to set position
```
Is this normal? I use i3 btw, which I'm hoping doesn't affect anything.

**Comment by acrisci** [comment]
This is very likely an upstream bug for Audacious. For instance, RhythmBox will give this behavior as well because they set the track id as a string instead of a dbus object path. I suspect that is what is going on here as well. I'll try to confirm this and help you with an issue upstream.

**Comment by acrisci** [comment]
If this is a common enough issue with the players, maybe we should try to convert the string to an object path.

**Comment by acrisci** [comment]
Yeah I think [this is the problem](https://github.com/audacious-media-player/audacious-plugins/blob/6823e29bc8da7a4b8ffea6d3abcd3f1b342f9716/src/mpris2/plugin.cc#L155).

**Comment by UtkarshVerma** [comment]
@acrisci Yes, that would indeed be better. Even Clementine yielded the same result.

**Comment by UtkarshVerma** [comment]
These are the results of fetching metadata in audacious vs clementine:
```sh
➜  ~ playerctl metadata       
{'bitrate': <320>, 'mpris:artUrl': <'file:///tmp/clementine-art-Q13827.jpg'>, 'mpris:length': <int64 301000000>, 'mpris:trackid': <'/org/mpris/MediaPlayer2/Track/63'>, 'xesam:album': <'Tougenkyou Alien'>, 'xesam:artist': <['serial TV drama']>, 'xesam:comment': <['#NIPPONSEI @ IRC.RIZON.NET']>, 'xesam:contentCreated': <'2018-05-06T10:36:44'>, 'xesam:genre': <['Anime']>, 'xesam:title': <'Tougenkyou Alien'>, 'xesam:trackNumber': <1>, 'xesam:url': <'file:///home/utkarsh/Music/Tougenkyou Alien.mp3'>, 'year': <2011>}%
➜  ~ playerctl metadata
{'xesam:title': <'Rolling Star'>, 'xesam:artist': <['Yui']>, 'xesam:album': <'Bleach'>, 'xesam:url': <'file:///home/utkarsh/Music/Rolling%20Star.mp3'>, 'mpris:length': <int64 190124000>, 'mpris:trackid': <'/org/mpris/MediaPlayer2/CurrentTrack'>}% 
```

**Comment by UtkarshVerma** [comment]
@acrisci I'm testing this new commit right now.

**Comment by acrisci** [comment]
aa1e25d should fix it too.
