### ISSUE TITLE
Any plans for `cmus`?

### ISSUE THREAD

**Issue by UtkarshVerma** [acrisci/playerctl#76]
I noticed that `playerctl` currently doesn't support `cmus`. Are there any plans for it?

**Comment by acrisci** [comment]
Cmus claims mpris support so it should work but i've never tested it.

**Comment by UtkarshVerma** [comment]
Cmus isn't supported by playerctl, therefore I an currently using `cmus-remote` for getting things done but having playerctl support would greatly improve my script.

**Comment by vinnyA3** [comment]
`playerctl` works fine with `cmus`, which is great because I can now control the player with my media keys.

---

**playerctl version:**  `v0.6.0`
**cmus version:**  `cmus v2.8.0-rc0-88-gb595b8c`

**Comment by UtkarshVerma** [comment]
@vinnyA3 Thanks, you're a life saver!

**Comment by vinnyA3** [comment]
You're welcome @UtkarshVerma
