### ISSUE TITLE
`playerctl --all-players <command>` hangs if there is gwenview  showing image

### ISSUE THREAD

**Issue by Self-Perfection** [acrisci/playerctl#82]
https://github.com/KDE/gwenview allows control of slideshow playback via D-Bus Interface.

But somehow this breaks playerctl and `playerctl --all-players <command>` hangs. playerctl stops execution until killed.

Note: this happens only when there is selected image in Gwenview, not in simple "browse" mode.

**Comment by acrisci** [comment]
I think it's the dbus interface misbehaving. Closing in favor of #93 .

**Comment by Self-Perfection** [comment]
Well I gave it a bit more attention. I can still reproduce this but I was wrong with my first identification of trigger factors.

Apparently gwenview has to be launched with argument, specific path to file or folder. I can't figure out yet which paths trigger this error and which are not.

If "bad location" is opened in gwenview, it shows in console output
```
QDBusConnection: error: could not send signal to service "" path "/org/mpris/MediaPlayer2" interface "org.freedesktop.DBus.Properties" member "PropertiesChanged": Marshalling failed: Invalid object path passed in arguments
QDBusConnection: error: could not send reply message to service "": Marshalling failed: Invalid object path passed in arguments
```

and then on running `playerctl --all-players <command>` it shows
```
QDBusConnection: error: could not send reply message to service "": Marshalling failed: Invalid object path passed in arguments
```
again and apparently does not give `playerct` response, which stalls its execution.

Now it loooks more like a bug in Gwenview or KDE. I'm going to open bug in KDE bug tracker once I find reliable way to reproduce this.

**Comment by Self-Perfection** [comment]
This is quite weird bug, I can reproduce it with specific cyrillic character sequences in path like "/tmp/Фото_неразо/test.png" but a bit shorter variant works well "/tmp/Фото_не/test.png" works well.

I've found reliable way to reproduce and created https://bugs.kde.org/show_bug.cgi?id=402970
