### ISSUE TITLE
spotify void linux playerctl mpris was not provided

### ISSUE THREAD

**Issue by klapperys** [acrisci/playerctl#84]
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files

i am currently on void linux.  dbus is installed and working

**Comment by acrisci** [comment]
Spotify support comes and goes. Some user settings might turn it off, so experiment and let me know if something works.

Run this command:

```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```

If you see anything in that list related to spotify, then it's my bug and I'll investigate.

**Comment by klapperys** [comment]
thanks so much ! i run the command nothing spotify related thank you for your time ! ill just wait for spotify to support it again :(

**Comment by klapperys** [comment]
i just wanna add .i have playerctl on my arch setup and it works perfectly . i wonder if void linux has something to do with it

**Comment by acrisci** [comment]
I don't have spotify anymore, but the setting I was referring to was notifications. Make sure you have the notification daemon working (the command to test it is `notify-send`) and that notifications are enabled. The spotify config file is in `~/.config/spotify/prefs` I believe. Check if you have any differences there.

But if the name isn't on the session bus, there's nothing playerctl can do to communicate with the player. Let me know if you need more help filing an issue somewhere if it comes to that.

**Comment by klapperys** [comment]
im going to a terminal client for spotify thanks for all your help ! im closing the issue
