### ISSUE TITLE
Allow some kind of continuous output (à la tail -f)

### ISSUE THREAD

**Issue by roobre** [acrisci/playerctl#88]
Many users like me use playerctl to show media info on status bars, or other programs which are more resident than scripty. In this scenario, if you want responsiveness (like skipping songs) you need to execute playerctl really quickly (less than once per second). This is a waste of resources, since spawning processes can be expensive.

Could be possible to add a flag to make playerctl either subscribe (ideal, but complicated) or poll (less optimal, but easier) dbus and write the output continuously to stdout?

**Comment by acrisci** [comment]
Yes, I'm working on this right now actually. Your input would be appreciated. Please comment on #37 with your thoughts on the details.
