### ISSUE TITLE
Add a command for shuffle

### ISSUE THREAD

**Issue by acrisci** [acrisci/playerctl#92]
https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Property:Shuffle

```
# get the shuffle status ("on" or "off")
playerctl shuffle

# set the shuffle status to on
playerctl shuffle on

# set the shuffle status to off
playerctl shuffle off
```

**Comment by corbinmcneill** [comment]
Why was this closed? I might be interested in extending for shuffle functionality so long as it is still of interest.

**Comment by acrisci** [comment]
I already implemented it, sorry.

Let me know if you find something else you want to do. The remainder of the work for the next release is boring stuff like testing, finding memory leaks, writing documentation, writing examples. stuff like that.

For the release after, I'm going to do a TUI and a GUI but I haven't thought it through yet.
